dgi_actions.identifier.*:
  type: config_object
  label: 'Identifier'
  mapping:
    identifier_id:
      type: string
      label: 'Identifier ID'
    credentials:
      type: dgi_actions.credentials.[%parent.identifier_id]
    data_profile:
      type: mapping
      label: 'Data Profile'
      mapping:
        id:
          type: string
        data:
          type: dgi_actions.data_profile.[%parent.id]

dgi_actions.data_profile.*:
  type: mapping
  label: 'Data Profile'
  data:
    type: sequence
    label: 'Data Profile Fields'

dgi_actions.credentials.*:
  type: mapping
  label: 'Identifier Credentials'
  mapping:
    host:
      type: string
      label: 'Host URI'
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'
    shoulder:
      type: string
      label: 'Namespace/Shoulder'
    field:
      type: string
      label: 'Field mapping for the Identifier'
