dgi_actions.identifier.*:
  type: config_entity
  label: 'Identifier'
  mapping:
    status:
      type: boolean
      label: 'Status'
    dependencies:
      type: sequence
      label: 'Dependencies'
      sequence:
        type: string
    id:
      type: string
      label: 'Identifier ID'
    label:
      type: string
      label: 'Identifier Label'
    entity:
      type: string
      label: 'Entity Type'
    bundle:
      type: string
      label: 'Bundle Type'
    field:
      type: string
      label: 'Identifier Object Field'
    service_data:
      type: string
      label: 'Service Data'
    data_profile:
      type: string
      label: 'Data Profile'

dgi_actions.data_profile.*:
  type: config_entity
  label: 'Data Profile'
  mapping:
    label:
      type: string
    id:
      type: string
    entity:
      type: string
    bundle:
      type: string
    dataprofile:
      type: string
    data:
      type: sequence
      sequence:
        type: mapping
        mapping:
          key:
            type: string
          source_field:
            type: string

dgi_actions.data_profile_type.*:
  type: config_object
  label: 'Data Profile Type'
  mapping:
    label:
      type: string
    id:
      type: string
    fields:
      type: sequence
      sequence:
        type: mapping
        mapping:
          key:
            type: string
          label:
            type: string
          description:
            type: string

dgi_actions.service_data.*:
  type: config_entity
  label: 'Service Data'
  mapping:
    label:
      type: string
    id:
      type: string
    service_data_type:
      type: string
    data:
      type: dgi_actions.service_data_type.[service_data_type]


dgi_actions.service_data_type.*:
  type: config_object
  label: 'Service Data Type'
  mapping:
    label:
      type: string
    id:
      type: string
    state_key:
      type: string
    data:
      type: sequence
      sequence:
        type: mapping
        mapping:
          type:
            type: string
          data:
            type: "[%parent.type]"
          id:
            type: string
          label:
            type: string
          description:
            type: string

