dgi_actions.identifier.*:
  type: config_object
  label: 'Identifier'
  mapping:
    status:
      type: boolean
      label: 'Status'
    dependencies:
      type: sequence
      label: 'Dependencies'
    identifier_id:
      type: string
      label: 'Identifier ID'
    label:
      type: string
      label: 'Identifier Label'
    credentials:
      type: dgi_actions.credentials.[%parent.identifier_id]
    data_profile:
      type: mapping
      label: 'Data Profile'
      mapping:
        id:
          type: string
        data:
          type: dgi_actions.data_profile.[%parent.id]

dgi_actions.data_profile.*:
  type: mapping
  label: 'Data Profile'
  mapping:
    id:
      type: string
      label: 'Data Profile ID'
    data:
      type: sequence
      label: 'Data Profile Fields'

dgi_actions.credentials.*:
  type: mapping
  label: 'Identifier Credentials'
  mapping:
    label:
      type: string
      label: "Credentials Label"
    host:
      type: string
      label: 'Host URI'
    langcode:
      type: string
      label: 'Language Code'
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'
    shoulder:
      type: string
      label: 'Namespace/Shoulder'
    field:
      type: string
      label: 'Field mapping for the Identifier'
