dgi_actions.identifier.*:
  type: config_entity
  label: 'Identifier'
  mapping:
    identifier_id:
      type: string
      label: 'Identifier ID'
    data_profile:
      type: mapping
      label: 'Data Profile'
      mapping:
        id:
          type: string
        data:
          type: dgi_actions.data_profile.[%parent.id]

dgi_actions.data_profile.*:
  type: mapping
  label: 'Data Profile'

#node type
#bundle
#identifier type - ark/doi/etc
 # by default I need to create the ARK one, we can expand the rest
#data profile - erc/datacite/dc
 # by default I need to make the erc data profile, we can expand the rest
