dgi_actions.identifier.*:
  type: config_entity
  label: 'Identifier'
  mapping:
    id:
      type: string
      label: 'Identifier ID'
    label:
      type: string
      label: 'Identifier Label'
    entity:
      type: string
      label: 'Entity Type'
    bundle:
      type: string
      label: 'Bundle Type'
    field:
      type: string
      label: 'Identifier Object Field'
    service_data:
      type: string
      label: 'Service Data Entity ID'
    data_profile:
      type: string
      label: 'Data Profile Entity ID'

dgi_actions.data_profile.*:
  type: config_entity
  label: 'Data Profile'
  mapping:
    label:
      type: string
    id:
      type: string
    entity:
      type: string
    bundle:
      type: string
    data_profile:
      type: string
    data:
      type: dgi_actions.data_profile_type.[%parent.data_profile]

dgi_actions.data_profile_type.*:
  type: mapping
  label: 'Data Profile Type'

dgi_actions.service_data.*:
  type: config_entity
  label: 'Service Data'
  mapping:
    label:
      type: string
    id:
      type: string
    service_data_type:
      type: string
    data:
      type: dgi_actions.service_data_type.[%parent.service_data_type]


dgi_actions.service_data_type.*:
  type: mapping
  label: 'Service Data Type'

condition.plugin.dgi_actions_entity_persistent_identifier_populated:
  type: condition.plugin
  mapping:
    identifier:
      type: machine_name
      nullable: true


dgi_actions_action_identifier_base:
  type: mapping
  mapping:
    identifier_entity:
      type: machine_name

dgi_actions_action_mint_base:
  type: dgi_actions_action_identifier_base
  mapping:
    save_entity:
      type: boolean

dgi_actions_action_delete_base:
  type: dgi_actions_action_identifier_base
