dgi_actions.identifier.*:
  type: config_entity
  label: 'Identifier'
  mapping:
    status:
      type: boolean
      label: 'Status'
    dependencies:
      type: sequence
      label: 'Dependencies'
      sequence:
        type: string
    id:
      type: string
      label: 'Identifier ID'
    label:
      type: string
      label: 'Identifier Label'
    entity:
      type: string
      label: 'Entity Type'
    bundle:
      type: string
      label: 'Bundle Type'
    field:
      type: string
      label: 'Identifier Object Field'
    service_data:
      type: entity:dgiactions_servicedata
      label: 'Service Data'
    data_profile:
      type: entity:dgiactions_dataprofile
      label: 'Data Profile'

dgi_actions.data_profile.*:
  type: config_entity
  label: 'Data Profile'
  mapping:
    label:
      type: string
    id:
      type: string
    entity:
      type: string
    bundle:
      type: string
    data_profile_type:
      type: string
    data:
      type: dgi_actions.data_profile_type.[%parent.data_profile_type]

dgi_actions.data_profile_type.*:
  type: mapping
  label: 'Data Profile Type'

dgi_actions.service_data.*:
  type: config_entity
  label: 'Service Data'
  mapping:
    label:
      type: string
    id:
      type: string
    service_data_type:
      type: string
    data:
      type: dgi_actions.service_data_type.[%parent.service_data_type]


dgi_actions.service_data_type.*:
  type: mapping
  label: 'Service Data Type'


