dgi_actions.service_data_type.purl:
  type: mapping
  label: 'PURL Service Data'
  mapping:
    host:
      type: uri
      label: 'PURL Service Hostname'
      description: 'Host address for the PURL service endpoints.'
    apikey:
      label: 'API Key'
      type: string
      description: 'API key for the PURL service endpoints.'
    domain:
      label: 'PURL Domain'
      type: string
      description: 'Domain for the PURL service.'
    institution:
      label: 'PURL Institution Code'
      type: string
      description: 'Institution code for the PURL service.'
    target:
      label: 'PURL Target Hostname'
      type: uri
      description: 'Target site hostname for the PURL service.'

action.configuration.dgi_actions_mint_purl:
  type: dgi_actions_action_mint_base
action.configuration.dgi_actions_update_purl:
  type: dgi_actions_action_update_base
action.configuration.dgi_actions_delete_purl:
  type: dgi_actions_action_delete_base
